# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Ritika Lamba"
title_separator          : "-"
name                     : &name "Ritika Lamba"
description              : &description "MS Student at Case Western Reserve University. Focused on LLMs, Fairness, XAI, and Emotion-Aware AI."
url                      : "https://rxl895.github.io"
baseurl                  : ""
repository               : "rxl895/rxl895.github.io"

# Author Sidebar Info
author:
  avatar           : "images/Profile_Pic.png"
  name             : "Ritika Lamba"
  bio              : "MS Student at Case Western Reserve University (CWRU)"
  email            : "ritikalamba@hotmail.com"
  linkedin         : "ritika-lamba"
  github           : "rxl895"
  googlescholar    : "https://scholar.google.com/citations?user=JByuP9sAAAAJ"
  orcid            : "https://orcid.org/0000-0002-1234-5678"

# Site Settings
teaser                   : 
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

comments:
  provider               : false

atom_feed:
  hide                   : false

# SEO and Social
social:
  type                   : Person
  name                   : "Ritika Lamba"
  links:
    - "https://www.linkedin.com/in/ritika-lamba"
    - "https://scholar.google.com/citations?user=JByuP9sAAAAJ"
    - "https://orcid.org/0000-0002-1234-5678"
    - "https://github.com/rxl895"

# Analytics
analytics:
  provider               : false

# Content Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# Sass Settings
sass:
  sass_dir: _sass
  style: compressed

# Output Settings
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..6
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

compress_html:
  clippings: all
  ignore:
    envs: development
